baseURL: "https://tsiantakis.dev/"
title: "tsiantakis.dev"
theme: "PaperMod"
copyright: "Tsiantakis Michail Angelos"

enableRobotsTXT: true
sitemap:
  changefreq: "monthly"
  filename: "sitemap.xml"

minify:
  disableXML: true
  minifyOutput: true

params:
  env: "production"
  title: "Michail Angelos Tsiantakis"
  description: "
  I am Computer Science undergraduate at the University of Thessaly.
  This is my personal blog where I write about various projects and interests."
  keywords: ["Michail Angelos Tsiantakis","Blog","Tsiantakis","Developer","aggellos2001",
  "Coding","ÎœÎ¹Ï‡Î±Î®Î» Î†Î³Î³ÎµÎ»Î¿Ï‚ Î¤ÏƒÎ¹Î±Î½Ï„Î¬ÎºÎ·Ï‚","Î†ÏÎ¸ÏÎ±","Github page"]
  author: "Michail Angelos Tsiantakis"
  DateFormat: "January 2, 2006"
  defaultTheme: auto #dark,light,auto
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false

  
  socialIcons:
    - name: "github"
      url: "https://github.com/aggellos2001"
    - name: "twitter"
      url: "https://twitter.com/aggellos2001"
    - name: "medium"
      url: "https://medium.com/@aggellos2001"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/mtsiantakis/"
    - name: "rss"
      url: "/index.xml"

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

languages:
    en:
      languageName: "English"
      weight: 1
      taxonomies:
        category: categories
        tag: tags
        series: series
      menu:
        main:
          - name: Home
            url: /
            weight: 1
          - name: Blog
            url: archives/
            weight: 2
          - name: Search
            url: search/
            weight: 3
          - name: Tags
            url: tags/
            weight: 4
          - name: Categories
            url: categories/
            weight: 5
      profileMode:
        enabled: true
        title: "Welcome to my page ğŸ‘‹ğŸ»"
        subtitle: "My name is Michail Angelos Tsiantakis and I am currently
        studying Computer Science in the [Department of Digital Systems](https://ds.uth.gr/en/home/)
        at the University of Thessaly."
        imageUrl: "/assets/tall.png"
        imageTitle: "Michail Angelos Tsiantakis"
        # buttons:
        #  - name: "Blog"
        #    url: "archives/"


    # -------- GR - EL -------
    el:
      languageName: "Î•Î»Î»Î·Î½Î¹ÎºÎ¬"
      weight: 1
      taxonomies:
        category: categories
        tag: tags
        series: series
      menu:
        main:
          - name: "Î‘ÏÏ‡Î¹ÎºÎ®"
            url: "/"
            weight: 1
          - name: "Î†ÏÎ¸ÏÎ±"
            url: "archives/"
            weight: 2
          - name: "Î‘Î½Î±Î¶Î®Ï„Î·ÏƒÎ·"
            url: "search/"
            weight: 3
          - name: "Î•Ï„Î¹ÎºÎ­Ï„ÎµÏ‚"
            url: "tags/"
            weight: 4
          - name: "ÎšÎ±Ï„Î·Î³Î¿ÏÎ¯ÎµÏ‚"
            url: categories/
            weight: 5
      profileMode:
        enabled: true
        title: "ÎšÎ±Î»Ï‰ÏƒÎ¿ÏÎ¯ÏƒÎ±Ï„Îµ ÏƒÏ„Î·Î½ ÏƒÎµÎ»Î¯Î´Î± Î¼Î¿Ï… ğŸ‘‹ğŸ»"
        subtitle: "ÎŸÎ½Î¿Î¼Î¬Î¶Î¿Î¼Î±Î¹ ÎœÎ¹Ï‡Î±Î®Î» Î†Î³Î³ÎµÎ»Î¿Ï‚ Î¤ÏƒÎ¹Î±Î½Ï„Î¬ÎºÎ·Ï‚ ÎºÎ±Î¹ ÎµÎ¯Î¼Î±Î¹ Ï†Î¿Î¹Ï„Î·Ï„Î®Ï‚
             ÏƒÏ„Î¿ Ï„Î¼Î®Î¼Î± [Î¨Î·Ï†Î¹Î±ÎºÏÎ½ Î£Ï…ÏƒÏ„Î·Î¼Î¬Ï„Ï‰Î½](https://ds.uth.gr/) 
             ÏƒÏ„Î·Î½ Î›Î¬ÏÎ¹ÏƒÎ±."
        imageUrl: "/assets/tall.png"
        imageTitle: "ÎœÎ¹Ï‡Î±Î®Î» Î†Î³Î³ÎµÎ»Î¿Ï‚ Î¤ÏƒÎ¹Î±Î½Ï„Î¬ÎºÎ·Ï‚"
        # buttons:
        #  - name: "Blog"
        #    url: "archives/"
            