baseURL = "https://tsiantakis.dev/"
title = "tsiantakis.dev"
theme = "PaperMod"
copyright = "Michail Angelos Tsiantakis"


enableRobotsTXT = true
[sitemap]
changefreq = "monthly"
filename = "sitemap.xml"

[minify]
disableXML = true
minifyOutput = true

[params]
env = "production"
title = "Michail Angelos Tsiantakis"
keywords = [
    "Michail Angelos Tsiantakis",
    "Blog",
    "Tsiantakis",
    "Developer",
    "aggellos2001",
    "Coding",
    "ÎœÎ¹Ï‡Î±Î®Î» Î†Î³Î³ÎµÎ»Î¿Ï‚ Î¤ÏƒÎ¹Î±Î½Ï„Î¬ÎºÎ·Ï‚",
    "Î†ÏÎ¸ÏÎ±",
    "Github page",
]
author = "Tsiantakis Michail Angelos"
DateFormat = "January 2, 2006"
defaultTheme = "auto"
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = false
ShowWordCount = true
ShowRssButtonInSectionTermList = true
UseHugoToc = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = false
hidemeta = false
hideSummary = false
showtoc = true
tocopen = false

[[params.socialIcons]]
name = "Github"
url = "https://github.com/aggellos2001"
[[params.socialIcons]]
name = "Mastodon"
url = "https://mastodon.social/@aggellos2001"
[[params.socialIcons]]
name = "X"
url = "https://twitter.com/aggellos2001"
[[params.socialIcons]]
name = "LinkedIn"
url = "https://www.linkedin.com/in/mtsiantakis/"
[[params.socialIcons]]
name = "rss"
url = "/index.xml"
[[params.socialIcons]]
name = "rss"
url = "/el/index.xml"


[outputs]
home = ["HTML", "RSS", "JSON"]


# Language configuration
[languages]
[languages.en]
languageName = "English"
weight = 1
[languages.en.params]
displayFullLangName = true
[languages.en.taxonomies]
category = "categories"
tag = "tags"
series = "series"
[languages.en.menu]
[[languages.en.menu.main]]
name = "Home"
url = "/"
weight = 1
[[languages.en.menu.main]]
name = "Blog"
url = "blog/"
weight = 2
[[languages.en.menu.main]]
name = "Search"
url = "search/"
weight = 3
[[languages.en.menu.main]]
name = "Tags"
url = "tags/"
weight = 4
[[languages.en.menu.main]]
name = "Categories"
url = "categories/"
weight = 5
[[languages.en.menu.main]]
name = "Archive"
url = "archives/"
weight = 6
[languages.en.params.profileMode]
enabled = true
title = "Welcome to my page ğŸ‘‹ğŸ»"
subtitle = """My name is Michail Angelos Tsiantakis and I recently
graduated from the [Dept. of Digital Systems of the School of Tenchology](https://ds.uth.gr/en/home/)
        at the University of Thessaly."""
imageUrl = "/assets/tall.png"
imageTitle = "Michail Angelos Tsiantakis"

[languages.el]
languageName = "Î•Î»Î»Î·Î½Î¹ÎºÎ¬"
weight = 2
[languages.el.params]
displayFullLangName = true
[languages.el.taxonomies]
category = "categories"
tag = "tags"
series = "series"
[languages.el.menu]
[[languages.el.menu.main]]
name = "Î‘ÏÏ‡Î¹ÎºÎ®"
url = "/"
weight = 1
[[languages.el.menu.main]]
name = "Î†ÏÎ¸ÏÎ±"
url = "blog/"
weight = 2
[[languages.el.menu.main]]
name = "Î‘Î½Î±Î¶Î®Ï„Î·ÏƒÎ·"
url = "search/"
weight = 3
[[languages.el.menu.main]]
name = "Î•Ï„Î¹ÎºÎ­Ï„ÎµÏ‚"
url = "tags/"
weight = 4
[[languages.el.menu.main]]
name = "ÎšÎ±Ï„Î·Î³Î¿ÏÎ¯ÎµÏ‚"
url = "categories/"
weight = 5
[[languages.el.menu.main]]
name = "Î‘ÏÏ‡ÎµÎ¯Î¿"
url = "archives/"
weight = 6
[languages.el.params.profileMode]
enabled = true
title = "ÎšÎ±Î»ÏÏ‚ Î®ÏÎ¸Î±Ï„Îµ ÏƒÏ„Î·Î½ ÏƒÎµÎ»Î¯Î´Î± Î¼Î¿Ï… ğŸ‘‹ğŸ»"
subtitle = """ÎŸÎ½Î¿Î¼Î¬Î¶Î¿Î¼Î±Î¹ ÎœÎ¹Ï‡Î±Î®Î» Î†Î³Î³ÎµÎ»Î¿Ï‚ Î¤ÏƒÎ¹Î±Î½Ï„Î¬ÎºÎ·Ï‚ ÎºÎ±Î¹ ÎµÎ¯Î¼Î±Î¹ [Î±Ï€ÏŒÏ†Î¿Î¹Ï„Î¿Ï‚](/el/blog/2023/july/graduation/)
             Ï„Î¿Ï… Ï„Î¼Î®Î¼Î±Ï„Î¿Ï‚ [Î¨Î·Ï†Î¹Î±ÎºÏÎ½ Î£Ï…ÏƒÏ„Î·Î¼Î¬Ï„Ï‰Î½](https://ds.uth.gr/) 
             Ï„Î¿Ï… Î Î±Î½ÎµÏ€Î¹ÏƒÏ„Î®Î¼Î¹Î¿Ï… Î˜ÎµÏƒÏƒÎ±Î»Î¯Î±Ï‚ ÏƒÏ„Î·Î½ Î›Î¬ÏÎ¹ÏƒÎ±."""
imageUrl = "/assets/tall.png"
imageTitle = "ÎœÎ¹Ï‡Î±Î®Î» Î†Î³Î³ÎµÎ»Î¿Ï‚ Î¤ÏƒÎ¹Î±Î½Ï„Î¬ÎºÎ·Ï‚"


[markup.goldmark.renderer]
unsafe = true
